drop table if exists Users CASCADE;
CREATE TABLE Users
(
    id        bigint generated by default as identity,

    user_id varchar(50),
    user_name varchar(50),
    user_channel_id varchar(50),
    user_email varchar(50),
    refresh_token VARCHAR(250)
--     expiry_date TIMESTAMP NOT NULL
);