drop table if exists Users CASCADE;
CREATE TABLE Users
(
    id        bigint generated by default as identity,

    user_id varchar(50),
--     user_password varchar(100),
    user_name varchar(50),
    user_handler varchar(100),
    user_email varchar(50),
--     access_token VARCHAR(250) NOT NULL,
    refresh_token VARCHAR(250)
--     expiry_date TIMESTAMP NOT NULL
);